/* DOR-LIO project page — embedded-data fallback.
 *
 * Anonymized mirrors such as anonymous.4open.science serve this page with
 * `Content-Security-Policy: sandbox` (no allow-same-origin), so the document
 * has an opaque origin and the browser blocks every fetch()/XHR as a
 * cross-origin request. <script> loading is not CORS-gated, so downsampled
 * base64 copies of the maps live in data/embed/*.js (generated by
 * tools/build_embed.py). DOREmbed.loadBinary() pulls one on demand; the
 * regular streamed fetch is always tried first (see js/ply-loader.js). */
(function (global) {
  'use strict';

  global.DOR_EMBED = global.DOR_EMBED || {};
  const pending = {};

  function embedUrlFor(path) {
    const name = path.slice(path.lastIndexOf('/') + 1).replace(/\.[^.]+$/, '');
    return 'data/embed/' + encodeURIComponent(name) + '.js';
  }

  function loadScript(url) {
    if (pending[url]) return pending[url];
    pending[url] = new Promise((resolve, reject) => {
      const s = document.createElement('script');
      s.src = url;
      s.onload = resolve;
      s.onerror = () => { delete pending[url]; reject(new Error('no embedded copy: ' + url)); };
      document.head.appendChild(s);
    });
    return pending[url];
  }

  async function decodeBase64(b64) {
    // fetch() on data: URLs bypasses CORS, so it still works in the sandbox.
    try {
      const res = await fetch('data:application/octet-stream;base64,' + b64);
      if (res.ok) return new Uint8Array(await res.arrayBuffer());
    } catch (e) { /* fall back to manual decoding */ }
    const bin = atob(b64);
    const out = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
    return out;
  }

  async function loadBinary(url, onProgress, signal) {
    if (!(url in global.DOR_EMBED)) await loadScript(embedUrlFor(url));
    const b64 = global.DOR_EMBED[url];
    if (!b64) throw new Error('no embedded data for ' + url);
    const buf = await decodeBase64(b64);
    if (signal && signal.aborted) throw new Error('aborted');
    if (onProgress) onProgress(buf.length, buf.length);
    buf.fromEmbed = true;
    return buf;
  }

  global.DOREmbed = { loadBinary };
})(window);
